### ISSUE TITLE
Add 'primary' keyword to mattr.

### ISSUE THREAD

**Issue by lwilletts** [pockata/mmutils#5]
So you can always get the primary screen values regardless of what it is called.

I don't think this would cause any conflicts with display adapter names.

**Comment by pockata** [comment]
That's actually something that I've wanted to do for a while now.

I just pushed a few changes that implement this behavior in `lsm`. You can get the primary monitor (if specified via `xrandr`) with the `-p` flag.

```
$ lsm -p
VGA1
```

In it's current state the, when there's no primary monitor, `lsm` just returns empty output.

EDIT:
Come to think of it would an error be more appropriate for a response when there's no primary monitor?
Perhaps so we can do `lsm -p || echo "no primary monitor"`

What do you think?

**Comment by lwilletts** [comment]
Empty output with an error code return is the wmutils way, I would say to stick to that.

**Comment by lwilletts** [comment]
[Getting a segmentation fault when just calling `lsm` with no options now.](https://a.uguu.se/0SQIudISGo7X_26-06-19-21%3A08%3A34.png)

**Comment by pockata** [comment]
Nice catch!
I've fixed the issue and now `lsm` returns an error code with the `-p` param and no primary monitor specified.
