### ISSUE TITLE
mattr: add screennumber argument

### ISSUE THREAD

**Issue by prez** [pockata/mmutils#6]
It would be convienient to be able to query for the screennumber ([manpage](https://www.x.org/archive/X11R6.8.1/doc/X.7.html#sect4)).
Use case: [ffmpeg expects a string of the form](https://www.ffmpeg.org/ffmpeg-devices.html#x11grab) `:display_number.screen_number`.

Situation:
```
$ xrandr --listmonitors | sed 1d
 0: +*eDP-1 1920/293x1080/165+0+0  eDP-1
$ lsm
eDP-1
```
Expected output (not sure about the 'm'): 
```
$ mattr m $(lsm)
0
```
Thank you for writing such a great tool!

**Comment by pockata** [comment]
Hey @seitokaichou, thank you for the kind words. It makes me really happy to see someone else using this project.

I like your idea. It makes sense to have this functionality implemented in `mattr`.

I'm a bit swamped with other things at the moment, so I can't promise exactly when I can implement this.
PRs are always welcome though!

**Comment by lwilletts** [comment]
Would be a great addition. Not so sure I would use it personally, but might make sense in setups where you have a laptop connecting to an external source like a projector or monitor so names aren't consistent where you always want to treat those sources like a second display.

**Comment by pockata** [comment]
@lwilletts I believe the `primary` flag would be a better fit for something like this (if I was able to understand you correctly).

@seitokaichou I've created a PR (#7)  with the requested changes. I believe it's working, but before I update the docs and merge it, please give it a spin and check if it's working for you as well.

**Comment by lwilletts** [comment]
@pockata yes, on further thought my comment really doesn't make much sense at all as a secondary source i.e. hdmi out on a laptop will always be called `HDMI-0` or equiv. regardless of what is connected.

**Comment by prez** [comment]
@pockata I'm not sure why you're subtracting 1 in line 75. With just one monitor attached, `mattr d $(lsm)` prints `-1`, while xrandr gives ` 0: ...`

**Comment by pockata** [comment]
@seitokaichou Yeah, I see my mistake now. I incorrectly assumed that screen 0 is the root screen and that's why I subtracted 1 from the number. In reality there's not root screen, there's a root window (`lsw -r` from wmutils) and I had two external monitors attached to my laptop, yielding LVDS1 (the built-in monitor) to be inactive and thus skewing the numbers by 1.

I've pushed a new commit in the branch which correctly takes inactive monitors into account.

Let me know if you still have any issues.

**Comment by lwilletts** [comment]
Just tried the branch out, looks good to me. Already found a nice use case for this with dmenu, simply inputting `-s $(mattr d $(pfm))` works great, although I did discover a bug with its `-b` option, as it wouldn't go fully to bottom on my secondary screen, so had to calculate the Y coordinate manually. 

[Here's what I got so far.](https://github.com/lwilletts/fwm/blob/master/wmenu)

**Comment by prez** [comment]
It's working as expected for me too. 
Thank you for implementing my suggestion, interacting with you was a pleasure.

**Comment by pockata** [comment]
Thank you for the kind words. It really warms my heart that someone else finds my scribbles useful.
I'll update the manpage and create a new release when I merge the branch.
