### ISSUE TITLE
[Feature Request] option in mattr to print in the normal format

### ISSUE THREAD

**Issue by eepykate** [pockata/mmutils#8]
currently mattr (at least with the options whxy) prints in a format like

    1920 1080 0 0

What about an option to print like

    1920x1080+0+0

so it's easier to just insert where a command is asking for geometry?

**Comment by lwilletts** [comment]
Not a bad suggestion but you could use something like sed or awk to do character replacement on the spaces to get the result you need for now.

**Comment by pockata** [comment]
Hey @GaugeK, thanks for taking interest in `mmutils`

Like @lwilletts said, it's easy to achieve the requested feature by just using `awk` like so:

```bash
$ mattr whxy "HDMI2" | awk '{ print $1 "x" $2 "+" $3 "+" $4 }'
1920x1080+0+0
```
But that's a bit too much for my taste and the requested feature makes sense to be a part of `mattr`, so I've implemented the feature in the branch [standard-geometry](https://github.com/pockata/mmutils/tree/standard-geometry).

Take it for a spin and let me know if it works for you.

The proposed usage in the feature branch is:
```bash
$ mattr -g $(pfw)
```

**Comment by eepykate** [comment]
> Not a bad suggestion but you could use something like sed or awk to do character replacement on the spaces to get the result you need for now.

Yeah, you could, and that's what I've been doing. Sed is faster than awk in my experience so I use that.

---

> But that's a bit too much for my taste and the requested feature makes sense to be a part of mattr, so I've implemented the feature in the branch standard-geometry.

This seems to work exactly like I want, thank you. Would be great if this makes it to the main branch!

    maim -g $(mattr -g $(pfm)) png.png

vs

    maim -g $(mattr whxy "$(pfm)" | sed -e 's/ /+/g' -e "s/+/x/") png.png

Way cleaner & simpler.

**Comment by eepykate** [comment]
Also, don't feel like making a new issue so I'll just request it here, but what about an option in `mattr` to print the combined size of all screens?

I have a 1440x900 + 1920x1080 monitor next to eachother, so the output for me should look like `3360x1080`.

My specific usecase would be to make a window that takes up the full size of both my screens.

---

> Hey @GaugeK, thanks for taking interest in mmutils

No, thank you. This project is very useful & a much better solution than parsing xrandr.

I was originally using tudurom/disputils but I switched to this due to an issue which has now been fixed. (https://github.com/tudurom/disputils/issues/5)

**Comment by lwilletts** [comment]
Won't `wattr wh $(lsw -r)` suffice?

**Comment by eepykate** [comment]
Yes it will, I didn't think of using wmutils for this.

**Comment by pockata** [comment]
@GaugeK I've pushed a new release which includes your requested changes from the `standard-geometry` branch.

As for the option to print the combined size of the screens, it's a bit of an edge case which `mattr nwh $(lsw -r)` doesn't handle properly right now. I might address the issue in the future, but using `wattr` for now seems to handle the job pretty well.
